import { Button } from "@/components/ui/Button";
import Card, { CardContent, CardHeader } from "@/components/ui/Card";
import SyncIndicator from "@/components/ui/SyncIndicator";
import { BarChart, DownloadCloud, FileText, Filter } from "lucide-react";
import React from "react";
import { useAppContext } from "../../context/AppContext";

const TripReportPage: React.FC = () => {
  const { isLoading } = useAppContext();

  // Placeholder for report data
  const reportTypes = [
    {
      id: "daily",
      name: "Daily Trip Summary",
      description: "Overview of all trips for the current day",
    },
    {
      id: "weekly",
      name: "Weekly Performance",
      description: "Trip performance metrics for the past week",
    },
    {
      id: "monthly",
      name: "Monthly Analytics",
      description: "Detailed monthly trip analytics and trends",
    },
    {
      id: "financial",
      name: "Financial Report",
      description: "Revenue, costs and profitability analysis",
    },
    {
      id: "efficiency",
      name: "Efficiency Metrics",
      description: "Route efficiency and utilization metrics",
    },
    { id: "custom", name: "Custom Reports", description: "Build and save custom trip reports" },
  ];

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Trip Reports</h1>
          <p className="text-gray-600">Generate and analyze trip-related reports</p>
        </div>
        <div className="flex items-center space-x-3">
          <SyncIndicator />
          <Button variant="outline" icon={<Filter className="w-4 h-4" />}>
            Filter
          </Button>
          <Button icon={<DownloadCloud className="w-4 h-4" />} disabled={isLoading.trips}>
            Export Data
          </Button>
        </div>
      </div>

      {/* Available Report Types */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {reportTypes.map((report) => (
          <Card key={report.id}>
            <CardContent className="p-6">
              <div className="flex items-start">
                <div className="p-3 bg-blue-100 rounded-full mr-4">
                  {report.id === "custom" ? (
                    <FileText className="h-6 w-6 text-blue-600" />
                  ) : (
                    <BarChart className="h-6 w-6 text-blue-600" />
                  )}
                </div>
                <div className="flex-1">
                  <h3 className="text-lg font-semibold text-gray-900 mb-1">{report.name}</h3>
                  <p className="text-sm text-gray-600 mb-4">{report.description}</p>
                  <div className="flex justify-end">
                    <Button size="sm" variant="outline">
                      Generate
                    </Button>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Recent Reports */}
      <Card>
        <CardHeader title="Recent Reports" />
        <CardContent>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Report Name
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Type
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Generated
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Generated By
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {[1, 2, 3].map((index) => (
                  <tr key={index} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600">
                      {["Monthly Trip Summary", "Revenue Analysis", "Efficiency Report"][index - 1]}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {["Monthly Analytics", "Financial Report", "Efficiency Metrics"][index - 1]}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {`2023-07-${10 + index}`}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      Admin User
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      <Button
                        size="sm"
                        variant="outline"
                        icon={<DownloadCloud className="w-4 h-4" />}
                      >
                        Download
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default TripReportPage;
